### ISSUE TITLE
First two links are broken

### ISSUE THREAD

**Issue by kke** [vigo/awesome-c64#1]
c64warez.com - No idea what's going on there now:

![image](https://user-images.githubusercontent.com/224971/70144440-9c3f5580-16a6-11ea-88e0-80aa809cd5bf.png)

Bombjack.org/commodore - I suppose their ssl cert is broken:

![image](https://user-images.githubusercontent.com/224971/70144590-eaecef80-16a6-11ea-91d3-71d2cbfc998b.png)

**Comment by vigo** [comment]
hmmm... no idea... let's check frequently... if this continues in the next days, we'll remove link :)

**Comment by senf666** [comment]
still broken @vigo
